// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALEv0TMHSO2BGCzQFWyIFFEn3O5lZwXg8',
    appId: '1:946418076446:web:9a50d92dc6a3cff014570f',
    messagingSenderId: '946418076446',
    projectId: 'myportfolio-fc465',
    authDomain: 'myportfolio-fc465.firebaseapp.com',
    storageBucket: 'myportfolio-fc465.firebasestorage.app',
    measurementId: 'G-TMPJFMSTWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC-W4QIct8HUzBwu9ufjiPTyfIch9zPOk',
    appId: '1:946418076446:android:e883b1c63863897414570f',
    messagingSenderId: '946418076446',
    projectId: 'myportfolio-fc465',
    storageBucket: 'myportfolio-fc465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM-ZrUlDBQrefrBoBjMFvwZk6SRQP_xeg',
    appId: '1:946418076446:ios:089e007a5a6407a114570f',
    messagingSenderId: '946418076446',
    projectId: 'myportfolio-fc465',
    storageBucket: 'myportfolio-fc465.firebasestorage.app',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM-ZrUlDBQrefrBoBjMFvwZk6SRQP_xeg',
    appId: '1:946418076446:ios:089e007a5a6407a114570f',
    messagingSenderId: '946418076446',
    projectId: 'myportfolio-fc465',
    storageBucket: 'myportfolio-fc465.firebasestorage.app',
    iosBundleId: 'com.example.personalPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALEv0TMHSO2BGCzQFWyIFFEn3O5lZwXg8',
    appId: '1:946418076446:web:a39e95b4813a502514570f',
    messagingSenderId: '946418076446',
    projectId: 'myportfolio-fc465',
    authDomain: 'myportfolio-fc465.firebaseapp.com',
    storageBucket: 'myportfolio-fc465.firebasestorage.app',
    measurementId: 'G-YJ46K1HL2S',
  );

}